/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/3d_linkedin_logo.glb 
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-linkedin-logo-e8786a94c6a942c594696d58d8c59a50
Title: 3D Linkedin Logo
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/3d_linkedin_logo.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0.519, 0.751, 1.541]} rotation={[3.087, 0.055, -1.539]}>
        <group position={[0, 3, 6]} scale={0.843}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.glossy_linkedin}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.glossy_putih}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3d_linkedin_logo.glb");
