/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/my-prot-model2.glb 
*/

import React, { useState } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

const kaynUnwantedAnimations = [
  "Kayn_Crit",
  "Kayn_Attack3",
  "Kayn_Idle1_Slayer",
  "Kayn_Eye_Cycle",
  "Kayn_Spell2_Slayer_idle",
  "Kayn_Spell1_Dash",
  "Kayn_Spell2_Slayer_run",
  "Kayn_Channel_windup",
  "Kayn_Spell3_Run_In",
  "Kayn_Run_Slayer",
  "Kayn_Idle2",
  "Kayn_Idle2_Assassin",
  "Kayn_Spell2_Slayer",
  "Kayn_Spell2_Assassin_Cast",
  "Kayn_Spell4_Air",
  "Kayn_Spell3_Run_In",
  "Kayn_Idle1_Slayer",
  "Kayn_Spell4_Air",
  "Kayn_Spell3_Idle",
  "Kayn_Laugh_to_Idle",
  "Kayn_Channel",
  "Kayn_Spell1_exit_to_run",
  "Kayn_Idle1_Assassin",
  "Kayn_Spell3_Run",
  "Kayn_Run",
  "Kayn_Idle1_loop",
];

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("models/my-prot-model2.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  const [isAnimating, setIsAnimating] = useState(false);
  const [hovered, setHovered] = useState(false);

  const handleModelClick = (event) => {
    event.stopPropagation();
    if (cameraRef.current) {
      const targetPosition = [0.062, 0.973, 0.591]; // Position of Sketchfab_model006
      const targetLookAt = [0, 0, 0]; // Adjust this based on where you want the camera to look
      animateCamera(targetPosition, targetLookAt);
    }
  };

  const handleClick = (event) => {
    event.stopPropagation();
    if (isAnimating) return;

    const actionKeys = Object.keys(actions);
    if (actionKeys.length > 0) {
      const wantedAnimations = actionKeys.filter(
        (key) => !kaynUnwantedAnimations.includes(key)
      );
      const randomAnimation =
        wantedAnimations[Math.floor(Math.random() * actionKeys.length)];
      console.log(randomAnimation);
      const action = actions[randomAnimation];
      console.log(action);
      console.log(action);

      if (action) {
        setIsAnimating(true);
        action.repetitions = 1;
        action.reset().play();

        const animationDuration = action.getClip().duration * 1000;
        setTimeout(() => {
          setIsAnimating(false);
        }, animationDuration);
      }
    }
  };

  const handlePointerOver = () => {
    if (!isAnimating) {
      document.body.style.cursor = "pointer";
      setHovered(true);
    }
  };

  const handlePointerOut = () => {
    document.body.style.cursor = "default";
    setHovered(false);
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Ashtray_27" position={[0.487, 0.743, 1.35]} />
              <group
                name="Ashtray_Ash_30"
                position={[0.487, 0.752, 1.35]}
                scale={[1, 0.45, 1]}
              />
              <group
                name="Cactus_Pot_2"
                position={[-0.051, 0.743, 0.876]}
                rotation={[0, -0.736, 0]}
              >
                <group name="Cactus_0" position={[0.01, 0.122, 0.014]} />
                <group name="Cactus_Soil_1" position={[0.001, 0.123, -0.001]} />
              </group>
              <group
                name="Chair_51"
                position={[0.923, 0.008, 0.77]}
                rotation={[Math.PI, -0.416, Math.PI]}
                scale={[1.235, 1, 1.235]}
              >
                <mesh
                  name="Object_107"
                  geometry={nodes.Object_107.geometry}
                  material={materials.M_OfficeStool_Bin_2048}
                />
              </group>
              <group
                name="Cigarette_Normal_25"
                position={[0.481, 0.747, 1.504]}
                rotation={[1.002, 0.422, 0.998]}
                scale={0.5}
              />
              <group
                name="Cigarette_Stub_Bent_28"
                position={[0.446, 0.764, 1.309]}
                rotation={[-1.448, -0.189, -2.328]}
                scale={0.5}
              />
              <group
                name="Cigarette_Stub_Straight_29"
                position={[0.53, 0.766, 1.406]}
                rotation={[-1.697, -0.143, 0.343]}
                scale={0.5}
              />
              <group
                name="CigarettePack_Blue_26"
                position={[0.382, 0.752, 1.511]}
                rotation={[Math.PI, -1.189, -1.886]}
                scale={0.5}
              />
              <group
                name="CigarettePack_Brown_31"
                position={[0.451, 0.752, 1.464]}
                rotation={[0, -0.571, 1.574]}
                scale={0.5}
              />
              <group
                name="Clipboard_49"
                position={[0.996, 0.565, 0.619]}
                rotation={[-3.126, -1.002, -1.576]}
              >
                <group
                  name="Clipboard_Paper_48"
                  position={[0.006, -0.034, 0.001]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={0.381}
                />
              </group>
              <group
                name="Computer_5"
                position={[0.061, 0.743, 0.472]}
                rotation={[0, -0.387, 0]}
              />
              <group
                name="Computer_Mouse_4"
                position={[0.533, 0.743, 0.53]}
                rotation={[0, -0.169, 0]}
              />
              <group
                name="FileBox_Black_7"
                position={[-0.084, 0.743, 1.283]}
                rotation={[0, 1.531, 0]}
                scale={[1.096, 1, 1]}
              />
              <group
                name="FileBox_Green_8"
                position={[-0.075, 0.743, 1.398]}
                rotation={[-Math.PI, 1.512, -Math.PI]}
                scale={[1.096, 1, 1]}
              />
              <group
                name="FileBox_Label_Finished_9"
                position={[-0.084, 0.743, 1.281]}
                rotation={[0, 1.531, 0]}
                scale={[1.096, 1, 1]}
              />
              <group
                name="FileBox_Label_Unsorted_10"
                position={[-0.075, 0.743, 1.398]}
                rotation={[-Math.PI, 1.512, -Math.PI]}
                scale={[1.096, 1, 1]}
              />
              <group
                name="Keyboard_3"
                position={[0.488, 0.743, 0.925]}
                rotation={[0, 0.168, 0]}
              />
              <group
                name="Lamp01_57"
                position={[-0.039, 0.743, 1.563]}
                rotation={[0, 0.454, 0]}
              >
                <group
                  name="Lamp02001_56"
                  position={[0, 0.061, 0]}
                  rotation={[0, 0, 0.811]}
                >
                  <group
                    name="Lamp02002_55"
                    position={[0, 0.118, 0]}
                    rotation={[0, 0, -0.976]}
                  >
                    <group
                      name="Lamp02_54"
                      position={[0, 0.279, 0]}
                      rotation={[0, 0, -0.491]}
                    >
                      <group
                        name="Lamp_Holder001_53"
                        position={[0, 0.366, 0]}
                        rotation={[0, 0, -0.603]}
                      >
                        <group name="Lamp_Shade001_52" position={[0, 0.083, 0]}>
                          <mesh
                            name="Object_119"
                            geometry={nodes.Object_119.geometry}
                            material={materials["M_Lamps_CCTV_2048.001"]}
                          />
                        </group>
                        <mesh
                          name="Object_117"
                          geometry={nodes.Object_117.geometry}
                          material={materials["M_Lamps_CCTV_2048.001"]}
                        />
                      </group>
                      <mesh
                        name="Object_115"
                        geometry={nodes.Object_115.geometry}
                        material={materials["M_Lamps_CCTV_2048.001"]}
                      />
                    </group>
                    <mesh
                      name="Object_113"
                      geometry={nodes.Object_113.geometry}
                      material={materials["M_Lamps_CCTV_2048.001"]}
                    />
                  </group>
                  <mesh
                    name="Object_111"
                    geometry={nodes.Object_111.geometry}
                    material={materials["M_Lamps_CCTV_2048.001"]}
                  />
                </group>
                <mesh
                  name="Object_109"
                  geometry={nodes.Object_109.geometry}
                  material={materials["M_Lamps_CCTV_2048.001"]}
                />
              </group>
              <group
                name="Microphone_34"
                position={[0.445, 0.743, 1.958]}
                rotation={[0, 0.361, 0]}
              />
              <group
                name="Monitor_6"
                position={[0.103, 0.91, 0.502]}
                rotation={[0, -0.269, 0]}
              />
              <group
                name="Notebook_50"
                position={[0.235, 0.743, 1.171]}
                rotation={[0, 0.319, Math.PI / 2]}
              >
                <mesh
                  name="Object_105"
                  geometry={nodes.Object_105.geometry}
                  material={materials.M_Clipboard_Notepad_1024}
                  scale={0.924}
                />
              </group>
              <group
                name="Notepad_11"
                position={[0.363, 0.743, 1.741]}
                rotation={[-0.005, 1.388, 0.005]}
                scale={[0.381, 0.137, 0.381]}
              />
              <group
                name="PhotoFrame1_47"
                position={[-0.241, 1.628, 0.369]}
                rotation={[0, -1.571, 0]}
                scale={[0.992, 0.992, 1.118]}
              />
              <group
                name="PhotoFrame2_46"
                position={[-0.241, 1.27, -0.097]}
                rotation={[0, -1.571, 0]}
                scale={[0.992, 0.992, 1.118]}
              />
              <group
                name="PhotoFrame_10x15_12"
                position={[-0.034, 0.743, 1.116]}
                rotation={[Math.PI / 2, 0, -1.814]}
                scale={0.381}
              />
              <group
                name="PinBoard_24"
                position={[0.617, 0.744, 1.647]}
                rotation={[1.516, 1.57, -1.571]}
                scale={0.381}
              >
                <group
                  name="Paper_Fax1_13"
                  position={[0.433, 0.031, -0.442]}
                  rotation={[-0.02, -0.022, 0]}
                />
                <group
                  name="Paper_Fax2_14"
                  position={[-0.441, 0.037, 0.073]}
                  rotation={[-0.032, 0.035, 0]}
                />
                <group
                  name="Paper_Note_15"
                  position={[-0.117, 0.031, -0.374]}
                  rotation={[-0.047, -0.054, 0.003]}
                />
                <group
                  name="Photo_Child_16"
                  position={[0.443, 0.03, 0.199]}
                  rotation={[-0.068, 0.063, 0.004]}
                />
                <group
                  name="Photo_Family_17"
                  position={[-0.583, 0.03, -0.495]}
                  rotation={[-0.034, -0.059, -0.003]}
                />
                <group
                  name="Pin_Big1_18"
                  position={[0.192, 0.038, -0.433]}
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={2.627}
                />
                <group
                  name="Pin_Big2001_20"
                  position={[0.683, 0.043, -0.418]}
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={2.627}
                />
                <group
                  name="Pin_Big2_19"
                  position={[-0.591, 0.04, -0.475]}
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={2.627}
                />
                <group
                  name="Pin_Flat1001_22"
                  position={[0.483, 0.038, 0.226]}
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={2.627}
                />
                <group
                  name="Pin_Flat1_21"
                  position={[-0.437, 0.044, 0.092]}
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={2.627}
                />
                <group
                  name="Pin_Flat2_23"
                  position={[-0.116, 0.037, -0.358]}
                  rotation={[-Math.PI / 2, -1.571, 0]}
                  scale={2.627}
                />
              </group>
              <group
                name="Poster_Crumpled_45"
                position={[-0.246, 1.568, 1.317]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.619, 0.309, 0.619]}
              />
              <group name="Table_Rough_32" position={[0.213, 0.006, 1.171]}>
                <mesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="TapeRecorder_33"
                position={[0.035, 0.743, 1.904]}
                rotation={[-Math.PI, 1.358, -Math.PI]}
              />
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model001"
          position={[0.001, 0.741, 1.923]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.408}
        >
          <group
            name="ce6de248fdee413fae242a30c4473ab8fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode">
              <group
                name="POT_WOOD_LEGS"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              />
              <group
                name="POTHOS"
                position={[0.528, 48.985, 2.882]}
                scale={51.957}
              />
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model002"
          position={[-0.528, 0.361, 1.822]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.003}
        >
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="skinned_mesh_0">
                <group
                  name="GLTF_created_0"
                  position={[292.697, 127.785, 36.981]}
                  rotation={[0, Math.PI / 1.4, 0]}
                  scale={0.45}
                  onClick={handleClick}
                  onPointerOver={handlePointerOver}
                  onPointerOut={handlePointerOut}
                >
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_6"
                    geometry={nodes.Object_6.geometry}
                    material={materials.Kayn_Base_Mat}
                    skeleton={nodes.Object_6.skeleton}
                  />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Kayn_Base_Slayer_Mat}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Kayn_Base_Assassin_Mat}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.Kayn_Assassin_Hair_Mat}
                    skeleton={nodes.Object_9.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model003"
          position={[0.519, 0.751, 1.541]}
          rotation={[3.087, 0.055, -1.539]}
          scale={0.014}
        >
          <group
            name="react-logo-circlefbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode001" position={[0, -0.001, 0]}>
              <group
                name="Backdrop"
                position={[-17.091, 7.935, 0]}
                rotation={[-Math.PI / 2, 1.571, 0]}
                scale={[247.854, 247.854, 52.734]}
              />
              <group
                name="React-Logo"
                position={[0, 7.934, 0]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[39.166, 39.166, 52.734]}
              />
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model004"
          position={[-0.199, 1.346, 2.489]}
          rotation={[-Math.PI / 2, 0, 0.447]}
          scale={0.015}
          onClick={() =>
            window.open("https://www.github.com/Bassaamm", "_blank")
          }
          onPointerOver={handlePointerOver}
          onPointerOut={handlePointerOut}
        >
          <group name="root002">
            <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Curve012_0"
                position={[67.458, -39.358, -36.022]}
                rotation={[-3.037, -1.129, 0.099]}
                scale={-130.57}
              >
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.glossy_putih}
                  position={[0.039, 0.005, -0.019]}
                  rotation={[0, -0.023, 0.001]}
                />
                <mesh
                  name="Object_5"
                  geometry={nodes.Object_5.geometry}
                  material={materials.github}
                  position={[0.039, 0.005, -0.019]}
                  rotation={[0, -0.023, 0.001]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model005"
          position={[-0.255, 1.034, 2.841]}
          rotation={[1.576, 0, 0]}
          scale={0.878}
        >
          <group name="bda37831dbab481da75e6eaaaf56f7ecfbx" scale={0.01}>
            <group name="RootNode002">
              <group
                name="Computer1"
                rotation={[-Math.PI, 0, -Math.PI / 2]}
                scale={100}
              />
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model006"
          position={[0.062, 0.973, 0.591]}
          rotation={[-Math.PI / 2, 0, 1.193]}
          scale={0.347}
        >
          <group
            name="Collada_visual_scene_group"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="aa001">
              <mesh
                name="defaultMaterial"
                geometry={nodes.defaultMaterial.geometry}
                material={materials["01___Default"]}
              />
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model007"
          position={[-0.007, 0.749, 1.993]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.298}
        >
          <group name="Plant_5fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode003">
              <group
                name="Cylinder006"
                position={[0, 29.508, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  name="Cylinder006_Flowerpot5_0"
                  geometry={nodes.Cylinder006_Flowerpot5_0.geometry}
                  material={materials.Flowerpot5}
                />
              </group>
              <group
                name="Cylinder007"
                position={[0, 29.508, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  name="Cylinder007_Soil_0"
                  geometry={nodes.Cylinder007_Soil_0.geometry}
                  material={materials.Soil}
                />
              </group>
              <group
                name="Plane079"
                position={[6.759, 64.261, 0.198]}
                rotation={[0.001, 0.092, -0.021]}
                scale={9.764}
              >
                <mesh
                  name="Plane079_Haworthia_leaf_0"
                  geometry={nodes.Plane079_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane080"
                position={[7.775, 64.619, 0]}
                scale={9.764}
              >
                <mesh
                  name="Plane080_Haworthia_leaf_0"
                  geometry={nodes.Plane080_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane081"
                position={[10.86, 65.232, 2.26]}
                scale={9.764}
              >
                <mesh
                  name="Plane081_Haworthia_leaf_0"
                  geometry={nodes.Plane081_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane082"
                position={[12.104, 64.054, 3.318]}
                scale={9.764}
              >
                <mesh
                  name="Plane082_Haworthia_leaf_0"
                  geometry={nodes.Plane082_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane083"
                position={[5.971, 64.886, 1.901]}
                scale={9.764}
              >
                <mesh
                  name="Plane083_Haworthia_leaf_0"
                  geometry={nodes.Plane083_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane084"
                position={[4.304, 60.456, 1.74]}
                rotation={[0.016, -0.416, -0.023]}
                scale={8.008}
              >
                <mesh
                  name="Plane084_Haworthia_leaf_0"
                  geometry={nodes.Plane084_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane085"
                position={[1.782, 59.856, 0.724]}
                rotation={[0.031, -0.418, -0.005]}
                scale={8.008}
              >
                <mesh
                  name="Plane085_Haworthia_leaf_0"
                  geometry={nodes.Plane085_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane086"
                position={[2.36, 60.974, 9.754]}
                rotation={[0.001, -0.343, -0.015]}
                scale={8.008}
              >
                <mesh
                  name="Plane086_Haworthia_leaf_0"
                  geometry={nodes.Plane086_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane087"
                position={[1.282, 60.548, 2.534]}
                rotation={[0.001, -0.343, -0.015]}
                scale={8.008}
              >
                <mesh
                  name="Plane087_Haworthia_leaf_0"
                  geometry={nodes.Plane087_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane088"
                position={[3.086, 60.281, 0.633]}
                rotation={[0.001, -0.343, -0.015]}
                scale={8.008}
              >
                <mesh
                  name="Plane088_Haworthia_leaf_0"
                  geometry={nodes.Plane088_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane089"
                position={[3.086, 60.281, 0.633]}
                rotation={[0.001, -0.343, -0.015]}
                scale={8.008}
              >
                <mesh
                  name="Plane089_Haworthia_leaf_0"
                  geometry={nodes.Plane089_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane090"
                position={[-1.928, 62.186, -6.315]}
                rotation={[0.007, -0.197, -0.019]}
                scale={8.008}
              >
                <mesh
                  name="Plane090_Haworthia_leaf_0"
                  geometry={nodes.Plane090_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane091"
                position={[9.907, 60.932, 14.357]}
                rotation={[0.001, -0.343, -0.015]}
                scale={8.008}
              >
                <mesh
                  name="Plane091_Haworthia_leaf_0"
                  geometry={nodes.Plane091_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane092"
                position={[15.332, 61.042, 14.478]}
                rotation={[0.001, -0.343, -0.015]}
                scale={8.008}
              >
                <mesh
                  name="Plane092_Haworthia_leaf_0"
                  geometry={nodes.Plane092_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane093"
                position={[12.011, 62.956, 1.632]}
                rotation={[0.001, -0.343, -0.015]}
                scale={8.008}
              >
                <mesh
                  name="Plane093_Haworthia_leaf_0"
                  geometry={nodes.Plane093_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Plane094"
                position={[12.597, 63.01, 5.583]}
                rotation={[0.001, -0.343, -0.015]}
                scale={8.008}
              >
                <mesh
                  name="Plane094_Haworthia_leaf_0"
                  geometry={nodes.Plane094_Haworthia_leaf_0.geometry}
                  material={materials.Haworthia_leaf}
                />
              </group>
              <group
                name="Rocks001"
                position={[10.196, 53.726, -23.901]}
                rotation={[-0.24, -0.563, 1.988]}
                scale={6.939}
              >
                <mesh
                  name="Rocks001_Stone_0"
                  geometry={nodes.Rocks001_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks002"
                position={[-0.351, 53.531, -25.536]}
                rotation={[-1.56, 0.118, 1.406]}
                scale={6.566}
              >
                <mesh
                  name="Rocks002_Stone_0"
                  geometry={nodes.Rocks002_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks003"
                position={[21.253, 53.403, 13.344]}
                rotation={[0.03, -0.044, 0.016]}
                scale={6.566}
              >
                <mesh
                  name="Rocks003_Stone_0"
                  geometry={nodes.Rocks003_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks004"
                position={[19.155, 51.626, 18.031]}
                rotation={[-2.82, -1.068, -2.848]}
                scale={6.566}
              >
                <mesh
                  name="Rocks004_Stone_0"
                  geometry={nodes.Rocks004_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks005"
                position={[16.126, 52.881, 14.986]}
                rotation={[0.13, 0.327, 0.149]}
                scale={6.566}
              >
                <mesh
                  name="Rocks005_Stone_0"
                  geometry={nodes.Rocks005_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks006"
                position={[14.667, 52.39, 19.701]}
                rotation={[0.002, -0.747, -0.005]}
                scale={6.912}
              >
                <mesh
                  name="Rocks006_Stone_0"
                  geometry={nodes.Rocks006_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks007"
                position={[11.148, 52.524, 23.473]}
                rotation={[-0.065, -0.372, 0.217]}
                scale={5.188}
              >
                <mesh
                  name="Rocks007_Stone_0"
                  geometry={nodes.Rocks007_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks008"
                position={[-2.459, 52.117, -20.338]}
                rotation={[0.215, 0.81, -0.382]}
                scale={6.566}
              >
                <mesh
                  name="Rocks008_Stone_0"
                  geometry={nodes.Rocks008_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks009"
                position={[-5.792, 53.112, -26.013]}
                rotation={[0.075, 0.037, 2.074]}
                scale={6.566}
              >
                <mesh
                  name="Rocks009_Stone_0"
                  geometry={nodes.Rocks009_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks010"
                position={[-8.501, 53.06, -22.687]}
                rotation={[-0.127, 0.29, -0.131]}
                scale={6.566}
              >
                <mesh
                  name="Rocks010_Stone_0"
                  geometry={nodes.Rocks010_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks011"
                position={[25.289, 52.939, -3.428]}
                rotation={[0.019, -0.249, 0.001]}
                scale={6.566}
              >
                <mesh
                  name="Rocks011_Stone_0"
                  geometry={nodes.Rocks011_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks012"
                position={[-13.074, 53.108, -21.372]}
                rotation={[-1.405, -0.118, 0.265]}
                scale={6.566}
              >
                <mesh
                  name="Rocks012_Stone_0"
                  geometry={nodes.Rocks012_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks013"
                position={[-18.105, 52.221, -19.221]}
                rotation={[-0.538, 0.486, 2.492]}
                scale={6.566}
              >
                <mesh
                  name="Rocks013_Stone_0"
                  geometry={nodes.Rocks013_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks014"
                position={[-16.157, 52.547, -16.367]}
                rotation={[-2.877, -1.207, 2.378]}
                scale={6.566}
              >
                <mesh
                  name="Rocks014_Stone_0"
                  geometry={nodes.Rocks014_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks015"
                position={[-20.733, 52.31, -14.561]}
                rotation={[2.509, 1.188, -2.848]}
                scale={6.566}
              >
                <mesh
                  name="Rocks015_Stone_0"
                  geometry={nodes.Rocks015_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks016"
                position={[-24.626, 52.125, -9.581]}
                rotation={[-2.594, -0.932, -0.699]}
                scale={6.566}
              >
                <mesh
                  name="Rocks016_Stone_0"
                  geometry={nodes.Rocks016_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks017"
                position={[-23.537, 53.18, 4.546]}
                rotation={[0.205, 0.613, -0.331]}
                scale={6.566}
              >
                <mesh
                  name="Rocks017_Stone_0"
                  geometry={nodes.Rocks017_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks018"
                position={[-25.939, 52.293, -0.635]}
                rotation={[-0.227, -1.061, -1.057]}
                scale={6.566}
              >
                <mesh
                  name="Rocks018_Stone_0"
                  geometry={nodes.Rocks018_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks019"
                position={[-3.732, 54.027, -22.816]}
                rotation={[1.536, -0.486, -2.89]}
                scale={4.173}
              >
                <mesh
                  name="Rocks019_Stone_0"
                  geometry={nodes.Rocks019_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks020"
                position={[7.443, 52.771, -6.511]}
                rotation={[-0.041, -0.598, 0.128]}
                scale={5.321}
              >
                <mesh
                  name="Rocks020_Stone_0"
                  geometry={nodes.Rocks020_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks021"
                position={[-23.543, 52.952, 10.338]}
                rotation={[2.953, -0.627, 0.137]}
                scale={6.566}
              >
                <mesh
                  name="Rocks021_Stone_0"
                  geometry={nodes.Rocks021_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks022"
                position={[-18.849, 52.396, 15.223]}
                rotation={[0.806, -0.477, -0.414]}
                scale={6.566}
              >
                <mesh
                  name="Rocks022_Stone_0"
                  geometry={nodes.Rocks022_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks023"
                position={[-16.099, 52.646, 19.887]}
                rotation={[-0.081, 0.972, -1.365]}
                scale={6.566}
              >
                <mesh
                  name="Rocks023_Stone_0"
                  geometry={nodes.Rocks023_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks024"
                position={[-11.001, 52.444, 23.47]}
                rotation={[-0.331, 0.969, 0.133]}
                scale={6.566}
              >
                <mesh
                  name="Rocks024_Stone_0"
                  geometry={nodes.Rocks024_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks025"
                position={[-6.363, 51.319, 24.606]}
                rotation={[-1.501, -0.208, -0.37]}
                scale={6.566}
              >
                <mesh
                  name="Rocks025_Stone_0"
                  geometry={nodes.Rocks025_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks026"
                position={[0.95, 53.594, 15.457]}
                rotation={[-2.927, 0.81, -1.674]}
                scale={6.566}
              >
                <mesh
                  name="Rocks026_Stone_0"
                  geometry={nodes.Rocks026_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks027"
                position={[14.619, 53.405, 5.829]}
                rotation={[2.954, 1.271, -2.569]}
                scale={4.566}
              >
                <mesh
                  name="Rocks027_Stone_0"
                  geometry={nodes.Rocks027_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks028"
                position={[26.09, 52.291, 0.741]}
                rotation={[0.065, 1.18, 0.234]}
                scale={4.891}
              >
                <mesh
                  name="Rocks028_Stone_0"
                  geometry={nodes.Rocks028_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks029"
                position={[0.99, 52.032, 5.657]}
                rotation={[-2.782, -0.567, -3.031]}
                scale={4.39}
              >
                <mesh
                  name="Rocks029_Stone_0"
                  geometry={nodes.Rocks029_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks030"
                position={[-4.722, 51.538, -2.135]}
                rotation={[-2.941, 0.098, 2.952]}
                scale={4.871}
              >
                <mesh
                  name="Rocks030_Stone_0"
                  geometry={nodes.Rocks030_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks031"
                position={[-10.248, 53.226, 19.58]}
                rotation={[-3.132, 0.001, -3.04]}
                scale={6.566}
              >
                <mesh
                  name="Rocks031_Stone_0"
                  geometry={nodes.Rocks031_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks032"
                position={[-1.75, 52.036, 26.56]}
                rotation={[3.038, -0.191, -3.059]}
                scale={6.566}
              >
                <mesh
                  name="Rocks032_Stone_0"
                  geometry={nodes.Rocks032_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks033"
                position={[11.215, 52.034, 18.522]}
                rotation={[-1.854, -0.159, -0.743]}
                scale={4.88}
              >
                <mesh
                  name="Rocks033_Stone_0"
                  geometry={nodes.Rocks033_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks034"
                position={[-22.078, 53.627, 15.089]}
                rotation={[1.122, 0.413, -2.12]}
                scale={4.88}
              >
                <mesh
                  name="Rocks034_Stone_0"
                  geometry={nodes.Rocks034_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks035"
                position={[-26.194, 52.617, -5.961]}
                rotation={[1.082, 0.101, -1.323]}
                scale={4.88}
              >
                <mesh
                  name="Rocks035_Stone_0"
                  geometry={nodes.Rocks035_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks036"
                position={[2.057, 52.606, -22.283]}
                rotation={[2.442, 1.239, -2.832]}
                scale={3.447}
              >
                <mesh
                  name="Rocks036_Stone_0"
                  geometry={nodes.Rocks036_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks037"
                position={[24.014, 52.968, 10.074]}
                rotation={[0.519, -0.886, 0.307]}
                scale={4.485}
              >
                <mesh
                  name="Rocks037_Stone_0"
                  geometry={nodes.Rocks037_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks038"
                position={[15.68, 52.626, 3.14]}
                rotation={[-0.092, -0.719, 0.091]}
                scale={3.203}
              >
                <mesh
                  name="Rocks038_Stone_0"
                  geometry={nodes.Rocks038_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks039"
                position={[26.241, 52.262, 5.554]}
                rotation={[1.091, 0.137, 1.825]}
                scale={6.041}
              >
                <mesh
                  name="Rocks039_Stone_0"
                  geometry={nodes.Rocks039_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks040"
                position={[-25.664, 53.032, 6.488]}
                rotation={[1.842, -0.371, 0.786]}
                scale={4.88}
              >
                <mesh
                  name="Rocks040_Stone_0"
                  geometry={nodes.Rocks040_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks041"
                position={[-11.434, 52.835, 4.761]}
                rotation={[2.016, 0.005, 1.728]}
                scale={4.88}
              >
                <mesh
                  name="Rocks041_Stone_0"
                  geometry={nodes.Rocks041_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks042"
                position={[-10.204, 52.874, 9.621]}
                rotation={[1.957, -0.259, 1.164]}
                scale={4.88}
              >
                <mesh
                  name="Rocks042_Stone_0"
                  geometry={nodes.Rocks042_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks043"
                position={[-14.657, 52.621, -6.234]}
                rotation={[1.915, 0.251, 2.278]}
                scale={4.88}
              >
                <mesh
                  name="Rocks043_Stone_0"
                  geometry={nodes.Rocks043_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks044"
                position={[5.841, 54.106, -3.676]}
                rotation={[1.367, 0.388, -2.478]}
                scale={4.88}
              >
                <mesh
                  name="Rocks044_Stone_0"
                  geometry={nodes.Rocks044_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks045"
                position={[5.675, 54.052, 3.925]}
                rotation={[1.191, -0.21, -0.946]}
                scale={4.88}
              >
                <mesh
                  name="Rocks045_Stone_0"
                  geometry={nodes.Rocks045_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks046"
                position={[26.11, 52.546, -7.099]}
                rotation={[0.07, -0.3, 0.01]}
                scale={3.203}
              >
                <mesh
                  name="Rocks046_Stone_0"
                  geometry={nodes.Rocks046_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks047"
                position={[-20.003, 53.501, 17.794]}
                rotation={[1.122, 0.413, -2.12]}
                scale={4.88}
              >
                <mesh
                  name="Rocks047_Stone_0"
                  geometry={nodes.Rocks047_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks1002"
                position={[15.578, 52.519, -19.684]}
                rotation={[0.156, 0.473, -0.219]}
                scale={6.566}
              >
                <mesh
                  name="Rocks1002_Stone_0"
                  geometry={nodes.Rocks1002_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks1556"
                position={[19.525, 53.06, -15.997]}
                rotation={[-1.473, 0.065, 0.554]}
                scale={6.566}
              >
                <mesh
                  name="Rocks1556_Stone_0"
                  geometry={nodes.Rocks1556_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks2001"
                position={[11.493, 52.949, -10.19]}
                scale={6.566}
              >
                <mesh
                  name="Rocks2001_Stone_0"
                  geometry={nodes.Rocks2001_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks2626"
                position={[23.129, 53.413, -11.933]}
                rotation={[-0.028, 0.602, 0.022]}
                scale={6.566}
              >
                <mesh
                  name="Rocks2626_Stone_0"
                  geometry={nodes.Rocks2626_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks3021"
                position={[17.763, 54.144, -13.528]}
                rotation={[-0.661, -0.819, 1.7]}
                scale={6.566}
              >
                <mesh
                  name="Rocks3021_Stone_0"
                  geometry={nodes.Rocks3021_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks3583"
                position={[22.496, 53.043, -8.055]}
                rotation={[0, -0.484, 0.001]}
                scale={6.566}
              >
                <mesh
                  name="Rocks3583_Stone_0"
                  geometry={nodes.Rocks3583_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
              <group
                name="Rocks536"
                position={[5.023, 53.393, -25.18]}
                scale={6.566}
              >
                <mesh
                  name="Rocks536_Stone_0"
                  geometry={nodes.Rocks536_Stone_0.geometry}
                  material={materials.Stone}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model008"
          position={[0.124, 0.6, 1.02]}
          rotation={[-Math.PI / 2, 0.059, 0.838]}
          scale={0.1}
          onClick={() =>
            window.open("https://www.linkedin.com/in/bassamalqarni", "_blank")
          }
          onPointerOver={handlePointerOver}
          onPointerOut={handlePointerOut}
        >
          <group name="root003">
            <group name="GLTF_SceneRootNode003" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Cylinder007_0"
                position={[0, 3, 6]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.843}
              >
                <mesh
                  name="Object_4001"
                  geometry={nodes.Object_4001.geometry}
                  material={materials.glossy_linkedin}
                  position={[-1.331, -0.426, 1.498]}
                  rotation={[-1.656, 0.735, 0.045]}
                  scale={0.682}
                />
                <mesh
                  name="Object_5001"
                  geometry={nodes.Object_5001.geometry}
                  material={materials["glossy_putih.001"]}
                  position={[-1.331, -0.426, 1.498]}
                  rotation={[-1.656, 0.735, 0.004]}
                  scale={0.682}
                />
              </group>
            </group>
          </group>
        </group>
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          material={nodes.Text.material}
          position={[0.251, 0.752, 1.258]}
          rotation={[2.511, 1.226, -2.422]}
          scale={0.02}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/my-prot-model2.glb");
