/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/scene.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[2.714, 0.396, -3.171]} scale={0.01}>
        <group position={[-206.236, -14.705, 442.366]} scale={[3.64, 1, 5.206]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Merged_Geometry_10.geometry}
            material={materials["gray-light-carpet"]}
            position={[1.809, 2.702, 0.259]}
            rotation={[0, 1.571, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Merged_Geometry_11.geometry}
            material={materials["red-carpet"]}
            position={[-0.079, 2.693, 0.261]}
            rotation={[0, 1.571, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Merged_Geometry_12.geometry}
            material={materials["wall-livingroom-carpet"]}
            position={[-42.853, 2.707, 29.66]}
            rotation={[0, 1.571, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_12.geometry}
            material={materials["red-carpet"]}
            position={[0.498, -2.715, -0.193]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <group
          position={[-72.37, 42.679, 427.081]}
          rotation={[Math.PI, -0.335, Math.PI]}
        >
          <group
            position={[3.033, 226.785, -105.108]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={0.599}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.body001.geometry}
              material={materials.shirt}
              position={[0.153, 16.283, -51.267]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_2001.geometry}
              material={nodes.Cylinder_2001.material}
              position={[0.965, 83.675, -58.409]}
              rotation={[0.216, -0.167, 0]}
              scale={1.334}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["hand-15"].geometry}
              material={materials.skin}
              position={[-69.048, -69.333, 71.267]}
              rotation={[1.814, 0.306, -0.243]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["hand-15_2"].geometry}
              material={materials.skin}
              position={[57.193, -72.481, 62.327]}
              rotation={[-1.368, -0.04, -0.48]}
              scale={-1}
            />
          </group>
          <group
            position={[-28.406, 203.127, -55.277]}
            rotation={[-2.975, 0.518, 3.058]}
            scale={[0.385, 0.418, 0.418]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle.geometry}
              material={materials["laptop-frame"]}
              position={[0, -5.445, -85.575]}
              rotation={[-Math.PI / 9, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_2004.geometry}
              material={materials["Material.001"]}
              position={[0, -0.214, -81.435]}
              rotation={[-Math.PI / 9, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_3002.geometry}
              material={materials["laptop-frame"]}
              position={[0, -66.851, 15.835]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_4.geometry}
              material={materials["Material.001"]}
              position={[0, -62.816, -3.881]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.833}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_5.geometry}
              material={materials["laptop-pad"]}
              position={[0, -66.011, 62.638]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.833}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.skin}
            position={[20.08, 288.017, -133.479]}
            rotation={[0.398, -0.489, 0.195]}
            scale={0.599}
          />
          <group
            position={[11.087, 317.14, -114.138]}
            rotation={[0.398, -0.492, 0.195]}
            scale={0.599}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_12.geometry}
              material={materials.hair}
              position={[12.598, 6.379, 31.351]}
              rotation={[-0.1, 0.281, 0.204]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_13.geometry}
              material={materials.hair}
              position={[-21.984, 10.292, 29.165]}
              rotation={[-0.038, -0.411, 3.029]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_14.geometry}
              material={materials["Material.001"]}
              position={[-21.34, 1.118, 28.721]}
              rotation={[0, -Math.PI / 9, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_15.geometry}
              material={materials["Material.001"]}
              position={[11.672, 1.118, 30.38]}
              rotation={[0, Math.PI / 9, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_16.geometry}
              material={materials.hair}
              position={[38.422, -12.667, -8.066]}
              rotation={[-Math.PI, 0, 0]}
              scale={-1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_2002.geometry}
              material={materials.hair}
              position={[34.854, 14.428, 27.348]}
              rotation={[-3.116, 0.606, -0.136]}
              scale={[-1, -1, -1.363]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_3.geometry}
              material={materials.hair}
              position={[-3.714, -39.927, -45.365]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_4.geometry}
              material={materials.hair}
              position={[50.426, 1.418, 12.411]}
              rotation={[3.095, 0.34, 0.024]}
              scale={[-1, -1, -1.141]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_5.geometry}
              material={materials.hair}
              position={[-48.331, 23.059, 12.151]}
              rotation={[-0.093, 0.348, -0.483]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_6.geometry}
              material={materials.hair}
              position={[12.611, 21.847, 28.499]}
              rotation={[0.372, -0.791, 1.733]}
              scale={[1, 1, 0.779]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube002.geometry}
              material={materials.hair}
              position={[-4.847, -22.512, 35.868]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube003.geometry}
              material={materials.hair}
              position={[-52.32, 1.479, 8.653]}
              rotation={[-0.093, 0.348, 0.238]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube004.geometry}
              material={materials.hair}
              position={[-44.386, -12.667, -6.069]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sphere_2.geometry}
              material={materials.skin}
              position={[-2.883, -8.507, -8.675]}
            />
          </group>
          <group
            position={[19.101, 279.414, -130.472]}
            rotation={[-1.13, -0.241, -0.469]}
            scale={0.351}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder.geometry}
              material={materials["Material.001"]}
              position={[72.074, -48.408, 2.681]}
              rotation={[0, 0, -0.175]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_2.geometry}
              material={materials["Material.001"]}
              position={[-76.467, -48.31, 2.681]}
              rotation={[0, 0, 0.262]}
            />
            <group
              position={[55.954, -61.834, 1.78]}
              rotation={[Math.PI / 2, 1.484, -Math.PI / 2]}
              scale={0.7}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={materials["Material.001"]}
                position={[0, 0, -7.358]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_2003.geometry}
                material={materials["Material.001"]}
                position={[-1.204, -0.119, 8.506]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_3001.geometry}
                material={materials["Material.001"]}
                position={[-1.204, -0.119, 15.358]}
              />
            </group>
            <group
              position={[-58.298, -62.561, 1.559]}
              rotation={[Math.PI / 2, -1.396, -Math.PI / 2]}
              scale={0.7}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials.hair}
                position={[0, 0, -7.358]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_2002.geometry}
                material={materials.hair}
                position={[-1.204, -0.119, 8.506]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_3.geometry}
                material={materials.hair}
                position={[-1.204, -0.119, 15.358]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Torus.geometry}
              material={materials["Material.001"]}
              position={[-2.41, -33.305, 1.834]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[1.054, 1, 1]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leg.geometry}
            material={materials.pants}
            position={[18.736, 172.504, -132.169]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={0.599}
          />
          <group
            position={[-59.443, 20.607, 1.955]}
            rotation={[-0.087, -Math.PI / 6, -0.175]}
            scale={0.717}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_2001.geometry}
              material={nodes.Cube_2001.material}
              position={[-0.123, -11.499, 2.05]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_3001.geometry}
              material={materials.skin}
              position={[-0.072, 25.369, -26.102]}
              rotation={[-0.175, 0, 0]}
              scale={0.653}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry_2001.geometry}
              material={nodes.Merged_Geometry_2001.material}
              position={[13.814, -10.785, 5.056]}
              rotation={[-0.001, 0.53, 0.151]}
              scale={1.394}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry001.geometry}
              material={nodes.Merged_Geometry001.material}
              position={[0.001, -0.599, -9.515]}
              rotation={[-0.001, 0.53, 0.151]}
              scale={1.394}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_2001.geometry}
              material={nodes.Rectangle_2001.material}
              position={[-0.006, -27.499, 0.541]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group
            position={[-27.412, 27.458, -30.035]}
            rotation={[-2.83, 0.2, -0.488]}
            scale={-0.717}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_2.geometry}
              material={nodes.Cube_2.material}
              position={[-0.123, -11.499, 2.05]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_3.geometry}
              material={materials.skin}
              position={[-2.989, 24.835, -28.736]}
              rotation={[-Math.PI / 9, 0, 0.087]}
              scale={0.653}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry.geometry}
              material={nodes.Merged_Geometry.material}
              position={[-0.253, -0.734, -9.574]}
              rotation={[2.949, 0.316, -0.426]}
              scale={-1.394}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry_2.geometry}
              material={nodes.Merged_Geometry_2.material}
              position={[13.34, -10.98, 4.383]}
              rotation={[2.949, 0.316, -0.426]}
              scale={-1.394}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_2.geometry}
              material={nodes.Rectangle_2.material}
              position={[-0.006, -27.499, 0.541]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
        </group>
        <group
          position={[5.62, 120.492, 640.235]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.back.geometry}
            material={materials["cream-soga"]}
            position={[-126.87, 23.149, -118.333]}
            rotation={[0, -1.571, 0]}
            scale={[1.01, 0.936, 0.982]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.back001.geometry}
            material={materials["cream-soga"]}
            position={[125.678, 23.149, -118.333]}
            rotation={[0, -1.571, 0]}
            scale={[1.264, 0.936, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bottom.geometry}
            material={materials["cream-soga"]}
            position={[1.045, -69.295, -7.062]}
            scale={[1, 1, 1.264]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.feet.geometry}
            material={materials["red-carpet"]}
            position={[307.344, -100.076, 145.351]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.feet001.geometry}
            material={materials["red-carpet"]}
            position={[307.344, -100.076, -155.483]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.feet002.geometry}
            material={materials["red-carpet"]}
            position={[-317.186, -100.076, 145.351]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.feet003.geometry}
            material={materials["red-carpet"]}
            position={[-317.186, -100.076, -155.483]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.piilow.geometry}
            material={materials["cream-soga"]}
            position={[121.766, -2.285, 49.285]}
            scale={[0.997, 1, 0.99]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pilow.geometry}
            material={materials["cream-soga"]}
            position={[-128.099, -2.285, 49.285]}
            scale={[0.929, 1, 1.096]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.side.geometry}
            material={materials["cream-soga"]}
            position={[296.736, 29.074, -8.326]}
            scale={[1, 1, 1.264]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.side001.geometry}
            material={materials["cream-soga"]}
            position={[-296.736, 29.074, -8.326]}
            scale={[1, 1, 1.264]}
          />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -50]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.StandingLamp1_StandingLampOff_0.geometry}
              material={materials.StandingLampOff}
              position={[-374.396, 27.702, 366.907]}
              scale={2.604}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/scene.glb");
