/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chair.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Chair(props) {
  const { nodes, materials } = useGLTF("models/chair.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_107.geometry}
        material={materials.M_OfficeStool_Bin_2048}
        position={[0.923, 0.008, 0.77]}
        rotation={[Math.PI, -0.416, Math.PI]}
        scale={[1.235, 1, 1.235]}
      />
    </group>
  );
}

useGLTF.preload("models/chair.glb");
