/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/github.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Github(props) {
  const { nodes, materials } = useGLTF("models/github.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.199, 1.346, 2.489]}
        rotation={[-Math.PI / 2, 0, 0.447]}
        scale={0.015}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[67.458, -39.358, -36.022]}
            rotation={[-3.037, -1.129, 0.099]}
            scale={-130.57}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.glossy_putih}
              position={[0.039, 0.005, -0.019]}
              rotation={[0, -0.023, 0.001]}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.github}
              position={[0.039, 0.005, -0.019]}
              rotation={[0, -0.023, 0.001]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/github.glb");
