/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/lamp.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Lamp(props) {
  const { nodes, materials } = useGLTF("models/lamp.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.09, 0.74, 1.58]} rotation={[0, 0.454, 0]}>
        <group position={[0, 0.061, 0]} rotation={[0, 0, 0.811]}>
          <group position={[0, 0.118, 0]} rotation={[0, 0, -0.976]}>
            <group position={[0, 0.279, 0]} rotation={[0, 0, -0.491]}>
              <group position={[0, 0.366, 0]} rotation={[0, 0, -0.603]}>
                <mesh
                  geometry={nodes.Object_117.geometry}
                  material={materials["M_Lamps_CCTV_2048.001"]}
                />
                <mesh
                  geometry={nodes.Object_119.geometry}
                  material={materials["M_Lamps_CCTV_2048.001"]}
                  position={[0, 0.083, 0]}
                />
              </group>
              <mesh
                geometry={nodes.Object_115.geometry}
                material={materials["M_Lamps_CCTV_2048.001"]}
              />
            </group>
            <mesh
              geometry={nodes.Object_113.geometry}
              material={materials["M_Lamps_CCTV_2048.001"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_111.geometry}
            material={materials["M_Lamps_CCTV_2048.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Object_109.geometry}
          material={materials["M_Lamps_CCTV_2048.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/lamp.glb");
