/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/monitor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Monitor({ onClick, ...props }) {
  const { nodes, materials } = useGLTF("models/monitor.glb");
  return (
    <group onClick={onClick} {...props} dispose={null}>
      <group
        position={[0.062, 0.973, 0.591]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.347}
      >
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials["01___Default"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/monitor.glb");
