/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/note.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Notepad(props) {
  const { nodes, materials } = useGLTF("models/note.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.235, 0.743, 1.171]}
        rotation={[0, 0.319, Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Object_105.geometry}
          material={materials.M_Clipboard_Notepad_1024}
          scale={0.924}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/note.glb");
