/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/table.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Table(props) {
  const { nodes, materials } = useGLTF("models/table.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials["Material.002"]}
        position={[0.213, 0.006, 1.171]}
      />
    </group>
  );
}

useGLTF.preload("models/table.glb");
